### ISSUE TITLE
Training problems

### ISSUE THREAD

**Issue by jwc666** [zzh-tech/ESTRNN#33]
Traceback (most recent call last):
  File "c:/Users/ChenJiwang/acjw1/ESTRNN/ESTRNN/main.py", line 24, in <module>
    trainer.run()
  File "c:\Users\ChenJiwang\acjw1\ESTRNN\ESTRNN\train\trainer.py", line 36, in run
    process(self.para)
  File "c:\Users\ChenJiwang\acjw1\ESTRNN\ESTRNN\train\dp.py", line 73, in process
    data = Data(para, device_id=0)
  File "c:\Users\ChenJiwang\acjw1\ESTRNN\ESTRNN\data\data.py", line 8, in __init__
    self.dataloader_train = module.Dataloader(para, device_id, ds_type='train')
  File "c:\Users\ChenJiwang\acjw1\ESTRNN\ESTRNN\data\gopro_ds_lmdb.py", line 94, in __init__
    para.centralize, para.normalize)
  File "c:\Users\ChenJiwang\acjw1\ESTRNN\ESTRNN\data\gopro_ds_lmdb.py", line 32, in __init__
    self.env_blur = lmdb.open(self.datapath_blur, map_size=1099511627776)
lmdb.Error: C:\Users\ChenJiwang\acjw1\ESTRNN\ESTRNN\dataset\gopro_ds_lmdb\gopro_ds_train: ���̿ռ
䲻�㡣

**Comment by jwc666** [comment]
When I run this code on windows, the system reports this error.

**Comment by zzh-tech** [comment]
Hi, it seems that lmdb is not compatible with Windows system.
